# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  # web server
  server:
    build:
      context: .
      target: final # must use the same stage as Vite below
    ports:
      - 9003:80
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - laravel-network

   # database service
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

   # vite service
#  vite:
#    build:
#      context: .
#      target: final # must use the same stage as the web server above
#    user: "root"
#    volumes:
#      - .:/var/www/html
      # Keeps node_modules safe in Linux memory
#      - /var/www/html/node_modules
#    ports:
#      - 5173:5173 # Maps Vite out to Windows
#    environment:
#      - npm_config_cache=/tmp/.npm-cache
#      - VITE_DEV_SERVER_URL=http://host.docker.internal:5173 # only works from WSL command prompt, not Windows Powershell
#      - VITE_HMR_HOST=host.docker.internal # only works from WSL command prompt, not Windows Powershell
#    networks:
#      - laravel-network
    # Automatically installs packages and boots Vite on startup using NPM
#    command: sh -c "npm install && npm run dev"

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge
